### ISSUE TITLE
phiseg3D code

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [gigantenbein/UNet-Zoo#19]
wanted to ask if the phiseg3D code has been tested and works? I'm trying to run it on a custom 3D dataset and am getting errors in the intermediate conv layers...so just wanted to confirm if it works for anybody

**Comment by gigantenbein** [comment]
Hi!

The support for 3D networks is experimental at best.

I will archive this repository since I don't have any time to maintain it at the moment.
